### ISSUE TITLE
[ Feature ]react-query 적용

### ISSUE THREAD

**Issue by chae-dahee** [programmers-project-july/ShowMailer-FE#3]
## 어떤 기능인가요?
> 추가하려는 기능에 대해 간결하게 설명해주세요
PR #4 
Performances.ts, Filter.tsx 에서 react-query 사용했습니다.
기본적인 부분이지만, 올바른 사용법인지 잘 모르겠어서 멘토님께서 체크해주시면 감사할 것 같습니다!
@rhkdgns95 

## 작업 상세 내용

- [ ] TODO
- [ ] TODO
- [ ] TODO

**Comment by rhkdgns95** [comment]
@chae-dahee 

react-query 적용된 코드가 있어서, 주석 및 임시로직 주석처리하여 적용하였습니다 (참고 : #8)

올바른 사용법이라함은 API를 작성하신 후 useQuery, useMutation과 같이 react-query에서 실행하는 로직을 적용해주시면 됩니다.

검색과 조회의 경우 `useQuery`를 이용하며, 특정 이벤트를 통해 호출하는 경우 `useMutation`을 이용합니다.
해당 react-query가 적용된 부분에서 렌더링과 동시에 useQuery가 호출이 되며, 이에 queryKey와 queryFn을 넣어주어, 해당 query의 구분자와 해당 API의 결과 값인 데이터를 반환받습니다. 

`queryKey`의 경우, 어떤 queryFn이 실행되었는지에 대한 구분자로 이해해주시면 될 것 같습니다.
이는 향후 재요청을 하거나, 프론트에서 데이터를 캐싱 및 빠른 데이터 업데이트 전략을 이용할때에 구분자로 필요하게 됩니다. 

`queryFn`의 경우, 주로 API를 호출하는 함수를 선언해주면 됩니다.
(API를 호출하는 함수가 아닌, 데이터를 반환하는 함수가 되어도 문제가 없습니다)

**Comment by chae-dahee** [comment]
> @chae-dahee
> 
> react-query 적용된 코드가 있어서, 주석 및 임시로직 주석처리하여 적용하였습니다 (참고 : #8)
> 
> 올바른 사용법이라함은 API를 작성하신 후 useQuery, useMutation과 같이 react-query에서 실행하는 로직을 적용해주시면 됩니다.
> 
> 검색과 조회의 경우 `useQuery`를 이용하며, 특정 이벤트를 통해 호출하는 경우 `useMutation`을 이용합니다. 해당 react-query가 적용된 부분에서 렌더링과 동시에 useQuery가 호출이 되며, 이에 queryKey와 queryFn을 넣어주어, 해당 query의 구분자와 해당 API의 결과 값인 데이터를 반환받습니다.
> 
> `queryKey`의 경우, 어떤 queryFn이 실행되었는지에 대한 구분자로 이해해주시면 될 것 같습니다. 이는 향후 재요청을 하거나, 프론트에서 데이터를 캐싱 및 빠른 데이터 업데이트 전략을 이용할때에 구분자로 필요하게 됩니다.
> 
> `queryFn`의 경우, 주로 API를 호출하는 함수를 선언해주면 됩니다. (API를 호출하는 함수가 아닌, 데이터를 반환하는 함수가 되어도 문제가 없습니다)

네! 그럼 공연 api 받아올때는 useQuery,  좋아요 요청 보낼때는 useMutation을 이용한다고 이해했는데 맞을까요? 감사합니다!

**Comment by rhkdgns95** [comment]
> @chae-dahee 
네! 그럼 공연 api 받아올때는 useQuery,  좋아요 요청 보낼때는 useMutation을 이용한다고 이해했는데 맞을까요? 감사합니다!

네, 맞습니다.
쉽게 이해하기 위해서, Read와 Write용 API으로 구분하면 될 것 같습니다.
```
Read 기능 API : useQuery
Write 기능 API : useMutation
```
